### ISSUE TITLE
not fix and not legacy

### ISSUE THREAD

**Issue by TrySound** [seaneking/postcss-clearfix#3]
I like to use case with `before` and `after` that will clear margin collapsing. But legacy is not that thing I want.

**Comment by seaneking** [comment]
sorry I don't fully understand what you're getting at, can you provide a before/after code sample?

**Comment by TrySound** [comment]
```css
.el:before,
.el:after {
  content: '';
  display: table;
}

el:after {
  clear: both;
}

.inner {
  margin: 40px 0;
}
```
```jade
div.el
  div.inner content
```
