### ISSUE TITLE
Not only one selector

### ISSUE THREAD

**Issue by TrySound** [seaneking/postcss-clearfix#4]
Before
```css
.container,
.container-fluid {
  clear: fix;
}
```
After
```css
.container,
.container-fluid:after {
	content: '';
	display: table;
	clear: both;
}
```
